config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts do
    resources :maps
  end

  resources :users do
    resource :post
  end

  resources :tags

  root to: 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :user

	has_attached_file :picture,
		styles: { medium: "500x500#" },
		:storage => :s3,
		:s3_credentials => {
			:bucket => 'ma-instagram',
		    :access_key_id => Rails.application.secrets.s3_access_key_id,
		    :secret_access_key => Rails.application.secrets.s3_secret_access_key
		}

	validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
	has_and_belongs_to_many :tags

	def tag_list
	end

	def tag_list=(some_tags)
		return if some_tags.empty?

		some_tags.split(', ').each do |tag|
			self.tags << Tag.find_or_create_by(text: tag)
		end
	end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :posts

	def to_param
		text.delete('#')
	end
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :posts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

	def index
		@post = Post.find(params[:post_id])
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!, except: [:index]

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(params[:post].permit(:title, :location, :picture, :tag_list))
		@post.user = current_user
		@post.save

		redirect_to '/posts'
	end

	def show
		@post = Post.find(params[:id])
	end


end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	def show
		@tag = Tag.find_by!(text: '#' + params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pipster</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header class="global-header container">
		<a href="<%= posts_path %>" id="logo"><h1>Pipster</h1></a>

		<ul class="global-nav">
			<li>
				<%= link_to(new_post_path, class: 'new-post') do %>
					<span class="glyphicon glyphicon-camera"></span>
					New Post
				<% end %>
			</li>

			<% if user_signed_in? %>

			<li>
				<%= link_to(destroy_user_session_path, class: 'logout', method: :delete) do %>
					<span class="glyphicon glyphicon-remove-circle"></span>
					Sign Out
				<% end %>
			</li>

			<% else %>

			<li>
				<%= link_to(new_user_registration_path, class: 'new-user') do %>
					<span class="glyphicon glyphicon-heart"></span>
					Sign Up
				<% end %>
			</li>
			<li>
				<%= link_to(user_session_path, class: 'login') do %>
					<span class="glyphicon glyphicon-home"></span>
					Sign In
				<% end %>
			</li>

			<% end %>

		</ul>
	</header>

	<main class="wrapper container">

	<ul class="feedback">
	<% if flash[:notice] %>
		<li class="notice"><%= notice %></li>
	<% end %>
	<% if flash[:alert] %>
		<li class="alert"><%= alert %></li>
	<% end %>
	</ul>


		<%= yield %>

		<section class="load">
			<span class="glyphicon glyphicon-repeat"></span>
		</section>

	</main>

	<footer class="global-footer container">
		Copyright
	</footer>


	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


</body>
</html>

app/views/maps/index.html.erb
<section class="row map-page">
	<header class="col-xs-12">

		<h1>
			<strong><%= @post.title %></strong>
			<span class="glyphicon glyphicon-map-marker"></span>
			<%= @post.location %>
		</h1>

	</header>
</section>

<section class="row map-page">

	<aside class="col-sm-6">
		<figure>
			<%= image_tag @post.picture.url(:medium), class: "uploaded_pic" %>
		</figure>
	</aside>

	<article class="col-sm-6">
		<div id="map" data-id="<%= @post.id %>"></div>
	</article>

</section>

app/views/posts/_post.html.erb
<article class="post col-xs-12 col-sm-4">

	<header>
		<h3>
			<%= post.title %>
		</h3>
	</header>

	<figure>
		<%= image_tag post.picture.url(:medium), class: "uploaded_pic" %>
	</figure>

	<address>
		<%= link_to(post_maps_path(post.id)) do %>
			<span class="glyphicon glyphicon-map-marker"></span>
			<%= post.location %>
		<% end %>
	</address>

	<footer>

		<% if post.tags.any? %>
		<ul class="tags">
			<% post.tags.each do |tag| %>
			<li><%= link_to tag.text, tag %></li>
			<% end %>
		</ul>

	</footer>


	<% end %>

</article>

app/views/posts/index.html.erb
<% if user_signed_in? %>
	Welcome <%= current_user.email %>!
<% end %>

<% if @posts.any? %>
	<% @posts.reverse.in_groups_of(3, false) do |posts_triplet| %>

	<section class="row">
		<%= render posts_triplet %>
	</section>

	<% end %>
<% else %>
	<h2>No posts yet</h2>
<% end %>

app/views/posts/new.html.erb
<section class="row">

	<article class="col-xs-6">
	<%= form_for @post, html: { multipart: true } do |f| %>
		<p>
			<%= f.label :title %>
			<%= f.text_field :title %>
		</p>

		<p>
			<%= f.label :location %>
			<%= f.text_field :location %>
			<button id="get_location" name="button" type="button">
				<span class="glyphicon glyphicon-map-marker"></span>
				Get Location
			</button>
		</p>

		<p>
			<%= f.label :picture %>
			<%= f.file_field :picture %>
		</p>

		<p>
			<%= f.label :tag_list, 'Tags' %>
			<%= f.text_field :tag_list %>
		</p>

		<p>
			<%= f.submit 'Create Post' %>
		</p>
	<% end %>
	</article>

	<aside class="photo-area-container col-xs-6">
		<h2 id="name_area"></h2>
		<article id="photo_area"><span class="glyphicon glyphicon-camera"></span></article>
	</aside>

</section>

app/views/tags/show.html.erb
<h1>Posts tagged with <%= @tag.text %></h1>

<% if @tag.posts.any? %>
	<% @tag.posts.in_groups_of(3, false) do |posts_triplet| %>

	<section class="row">
		<%= render posts_triplet %>
	</section>

	<% end %>
<% else %>
	<h2>No posts yet</h2>
<% end %>